export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PROCUST_LIST_SUCCESS = 'PROCUST_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PROCUST_DETAILS_SUCCESS = 'PROCUST_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE';
